language: java
jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - mysql
  
before_install:
  - mysql -u root --password="" < sql/travis-init.sql

jobs:
    include:
        - stage: "Maven clean install"
        - script: mvn clean install

