language: java
jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - mysql
  
before_install:
  - mysql -u root --password="" < sql/travis-init.sql

jobs:
    include:
        - stage: Main job
            script: 
                - mvn clean install
                - mvn test -Pcomponent-tests

