language: java
jdk:
  - oraclejdk11

services:
  - mysql
  
before_install:
  - mysql -u root --password="" < test/travis.sql

notifications:  
  email:  
    recipients:  
    - $TRAVIS_EMAIL_JOOST
    on_success: always
    on_failure: always

script: mvn clean install
